version: '2.1'

x-logging: &default-logging
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

networks:
  monitor-net:
    driver: bridge

volumes:
  caddy_data: { }
#  loki_data: { }
#  prometheus_data: { }
#  grafana_data: { }

services:
  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: prometheus
    volumes:
      - ${APP_DIR}/prometheus/etc:/etc/prometheus
      - ${APP_DIR}/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=1y'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    expose:
      - 9090
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
    user: "1000"

  alertmanager:
    image: prom/alertmanager:v0.24.0
    container_name: alertmanager
    volumes:
      - ${APP_DIR}/alertmanager/etc:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    expose:
      - 9093
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter:v1.3.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:9.1.1
    container_name: grafana
    volumes:
      - ${APP_DIR}/grafana/data:/var/lib/grafana
      - ${APP_DIR}/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ${APP_DIR}/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
    user: "1000"

  pushgateway:
    image: prom/pushgateway:v1.4.3
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"


  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    expose:
      - 3100
    volumes:
      - ${APP_DIR}/loki:/etc/loki
#      - loki_data:/tmp/loki
    command: -config.file=/etc/loki/loki-config.yml
    environment:
      - TZ=Europe/Vienna
    networks:
      - monitor-net
    logging: *default-logging
    labels:
      org.label-schema.group: "monitoring"

  promtail:
    image: grafana/promtail:2.6.1
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - ${APP_DIR}/loki:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    networks:
      - monitor-net
    logging: *default-logging
    labels:
      org.label-schema.group: "monitoring"

  caddy:
    image: slothcroissant/caddy-cloudflaredns:2.6.1
    container_name: caddy
    ports:
      - "3000:3000"
      - "9090:9090"
      - "9093:9093"
      - "9091:9091"
      - "8888:8888"
    volumes:
      - ${APP_DIR}/caddy:/etc/caddy
      - caddy_data:/data
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH:-JDJhJDE0JE91S1FrN0Z0VEsyWmhrQVpON1VzdHVLSDkyWHdsN0xNbEZYdnNIZm1pb2d1blg4Y09mL0ZP}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - MON_DOMAIN=${MON_DOMAIN}
      - ACME_AGREE=true
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
    logging: *default-logging
